### ISSUE TITLE
DynamoDB Stream Consumer Race Condition with `shardEnded`

### ISSUE THREAD

**Issue by barryoneill** [laserdisc-io/fs2-aws#422]
I'm using `fs2.aws.dynamodb.package$#readFromDynamDBStream` to read from a ddb stream, and `fs2.aws.dynamodb#checkpointRecords` to checkpoint the records after processing. 

The following problem arises when there is a delay (in my case, intentional) in checkpointing the records, and the `software.amazon.kinesis.processor.ShardRecordProcessor#shardEnded` event fires.  fs2_aws correctly checkpoints the end of the shard, but then subsequent checkpoints of the previously emitted events will fail with: 

```
ava.lang.IllegalArgumentException: Could not checkpoint at extended sequence number {SequenceNumber: 554022700000000052561897332,SubsequenceNumber: 0} as it did not fall into acceptable range between the last checkpoint {SequenceNumber: SHARD_END,SubsequenceNumber: 0} and the greatest extended sequence number passed to this record processor {SequenceNumber: SHARD_END,SubsequenceNumber: 0}
```

We need to maintain a list of all in-flight commitable records, and evict them when fs2-aws checkpoints a `shardEnded` event.

**Comment by semenodm** [comment]
i think we don't need to store the list of all in-flight messages, just current number in atomic ref, every new emitted message should increment the counter and every checkpoint should decrement this. once shard observes END_OF_SHARD event it must check the current value in the counter and if it is 0, it is considered safe to end shard, however if it is >0 it must revisit it later, maybe the part of the state has to be some boolean flag indicating that END_OF_SHARD event has been received, this way every time counter hits 0 and this flag is true, we can finalize the shard .
As the result, this state has to be a part of commitable records, because this is where we do the checkpointing.

@barryoneill please review this

**Comment by barryoneill** [comment]
Looks like alpakka had to deal with the same issue https://github.com/akka/alpakka/pull/1667/files

**Comment by barryoneill** [comment]
Which exposes the fact that the `processRecords()` payload has a `isAtShardEnd` boolean

**Comment by barryoneill** [comment]
I suspect we should try and emulate alpakka's approach

**Comment by semenodm** [comment]
@barryoneill saying `alpakka approach`what exactly do you mean. AFAIK alpakka doesn't have kinesis integration. can you point me to the code ?

**Comment by barryoneill** [comment]
@semenodm sorry, I split my thoughts over multiple comments before that one - see https://github.com/akka/alpakka/pull/1667/files
